import{S as m,A as g,N as v}from"./assets/vendor-BuglDXfm.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))f(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const c of t.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&f(c)}).observe(document,{childList:!0,subtree:!0});function p(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function f(e){if(e.ep)return;e.ep=!0;const t=p(e);fetch(e.href,t)}})();let a=null,l=null,d=null;function L(){window.innerWidth<1440?a||(a=new m(".how-swiper",{modules:[g],slidesPerView:1.17,spaceBetween:16,loop:!0,autoplay:{delay:3e3,disableOnInteraction:!1}})):a&&(a.destroy(!0,!0),a=null)}function S(){window.innerWidth<1440?l||(l=new m(".gallery-swiper",{modules:[g],slidesPerView:1.2,spaceBetween:16,loop:!0,autoplay:{delay:3e3,disableOnInteraction:!1}})):(l&&(l.destroy(!0,!0),l=null),l=new m(".gallery-swiper",{modules:[v],slidesPerView:3.4,spaceBetween:24,loop:!0,navigation:{nextEl:".gallery-next",prevEl:".gallery-prev"}}))}function E(){window.innerWidth<1440?d||(d=new m(".features-swiper",{modules:[g],slidesPerView:1.2,spaceBetween:16,loop:!0,autoplay:{delay:3e3,disableOnInteraction:!1}})):d&&(d.destroy(!0,!0),d=null)}function y(){L(),S(),E()}y();window.addEventListener("resize",()=>{clearTimeout(window.swiperResize),window.swiperResize=setTimeout(()=>{a&&(a.destroy(!0,!0),a=null),l&&(l.destroy(!0,!0),l=null),d&&(d.destroy(!0,!0),d=null),y()},200)});document.addEventListener("DOMContentLoaded",()=>{const u=document.querySelector(".menu-button"),s=u.querySelector(".icon"),p=document.querySelector(".modal"),f=document.querySelectorAll(".menu-list-item"),e=document.querySelector(".header");let t=!1;const c=`
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M6 8H17M6 16H17M6 12H17" stroke="#232323" stroke-linecap="square" />
</svg>
    `,n=`
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M8 8L12 12M12 12L8 16M12 12L16 16M12 12L16 8" stroke="#232323" stroke-linecap="square" stroke-linejoin="round" />
</svg>
    `;u.addEventListener("click",()=>{t=!t,s.innerHTML=t?n:c,t?o():i()}),f.forEach(w=>w.addEventListener("click",()=>{i(),s.innerHTML=c,t=!1})),window.addEventListener("scroll",r);function o(){p.style.display="block"}function i(){p.style.display="none"}function r(){e&&(window.scrollY>60?e.classList.add("header-scroll"):e.classList.remove("header-scroll"))}});document.addEventListener("DOMContentLoaded",()=>{function u(){const n=document.getElementById("site-header");return n?n.offsetHeight:0}function s(n){const o=document.getElementById(n);if(!o)return;const i=u(),r=o.getBoundingClientRect().top+window.pageYOffset-i;window.scrollTo({top:r,behavior:"smooth"})}document.querySelectorAll(".navigation-item a").forEach(n=>{n.addEventListener("click",function(o){const i=this.getAttribute("href");if(!i)return;const[r,w]=i.split("#");if(!w)return;const h=window.location.pathname.split("/").pop();!(r===""||r==="./"||r===h||r==="./"+h)||!document.getElementById(w)||(o.preventDefault(),s(w),t(w))})});const f=document.querySelectorAll("section[id]"),e=document.querySelectorAll(".navigation-item");function t(n){e.forEach(i=>i.classList.remove("active"));const o=document.querySelector(`.navigation-item a[href*="#${n}"]`);o&&o.closest(".navigation-item").classList.add("active")}function c(){const n=window.pageYOffset+u()+100;f.forEach(o=>{const i=o.offsetTop,r=i+o.offsetHeight;n>=i&&n<r&&t(o.id)})}if(window.addEventListener("scroll",c),window.location.hash){const n=window.location.hash.substring(1);setTimeout(()=>{s(n),t(n)},300)}});
//# sourceMappingURL=index.js.map
